#https://hub.docker.com/r/microsoft/mssql-server
---
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU29-ubuntu-16.04
    container_name: my-mssql
    env_file: .env
    ports:
      - 1433:1433
    volumes:
      - ./mssql_data/data:/var/opt/mssql/data
      - ./mssql_data/log:/var/opt/mssql/log
      - ./mssql_data/secrets:/var/opt/mssql/secrets